apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: __namespace__
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: nginx
      port: 32001
      targetPort: 32001
      nodePort: 32001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: odp-nginx-sec
        secret:
          secretName: odp-nginx-sec
      containers:
        - name: nginx
          image: '__docker_registry_server__/datanimbus.io.nginx:__release__'
          ports:
            - containerPort: 32001
          volumeMounts:
            - name: odp-nginx-sec
              mountPath: "/app/keys"
              readOnly: true
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret